* Added groq for challenge overview
railroadmedia/musora-content-services pull request #21
Opened 2024-08-30 16:49 UTC by MeenuDhanoa

2024-08-30 20:24 UTC, adrian-musora requested changes

2024-08-30 20:24 UTC, adrian-musora commented on src/index.js
> +  fetchChallengeOverview,
We need this.
```suggestion
  fetchLiveEvent,
  fetchChallengeOverview,
```

2024-08-30 20:24 UTC, adrian-musora commented on src/index.js
> +    fetchChallengeOverview,
```suggestion
    fetchLiveEvent,
    fetchChallengeOverview,
```

2024-08-30 20:24 UTC, adrian-musora commented on src/services/sanity.js
> +export async function fetchChallengeOverview(id) {
This is an ignorant question that i couldn't find a quick answer to. Is this method intended to only get `Challenge` type content? If so, I'd prefer if we moved the fields to the `contentTypeConfig.js` to maintain the design.

2024-09-02 05:46 UTC, csillaj approved these changes

2024-09-02 15:38 UTC, Joels-code commented
I agree with Adrians points. I will re-review once the changes are made

2024-09-03 16:42 UTC, adrian-musora approved these changes

2024-09-03 16:42 UTC, adrian-musora commented on src/contentTypeConfig.js
> +            'description',
Description is an object field, so has a complex structure. We may update the format later, but for the moment are using the the raw html. 
```suggestion
            `"description": ${descriptionField}`,
```

2024-09-03 17:43 UTC, merged